name: "CI Deep"

env:
  MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * 3,6" # at 3:00am UTC on Wednesday and Saturday
  workflow_dispatch:
    inputs:
      integrationFuzzRuns:
        default: "100000"
        description: "Integration: number of fuzz runs."
        required: false
      invariantRuns:
        default: "50000"
        description: "Invariant runs: number of sequences of function calls generated and run."
        required: false
      invariantDepth:
        default: "200"
        description: "Invariant depth: number of function calls made in a given run."
        required: false
      forkFuzzRuns:
        default: "20"
        description: "Fork: number of fuzz runs."
        required: false

jobs:
  build:
    uses: "sablier-labs/gha-utils/.github/workflows/forge-build.yml@main"

  test-invariant:
    needs: ["build"]
    uses: ./.github/workflows/forge-test.yml
    with:
      foundry-invariant-depth: ${{ fromJSON(inputs.invariantDepth || '200') }}
      foundry-invariant-runs: ${{ fromJSON(inputs.invariantRuns || '50000') }}
      foundry-profile: "test-optimized"
      foundry-version: "nightly"
      match-path: "tests/invariant/**/*.sol"
      name: "Invariant tests"
